<div class="pull-right paymentMethodImg"> 
<img height="30" class="pull-right" src="<?php echo $this->getSkinUrl('images/payment/master_card.png');?>" alt="img" > 
<img height="30" class="pull-right" src="<?php echo $this->getSkinUrl('images/payment/paypal.png');?>" alt="img" > 
<img height="30" class="pull-right" src="<?php echo $this->getSkinUrl('images/payment/american_express_card.png');?>" alt="img" > 
<img  height="30" class="pull-right" src="<?php echo $this->getSkinUrl('images/payment/discover_network_card.png');?>" alt="img" > 
<img  height="30" class="pull-right" src="<?php echo $this->getSkinUrl('images/payment/google_wallet.png');?>" alt="img" > 
</div>