<?php $skinUrl = $this->getSkinUrl("titan/");?>
<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
<!--[if lt IE 9]>
  <script src="<?php echo $skinUrl ?>js/html5shiv.js"></script>
  <script src="<?php echo $skinUrl ?>js/respond.min.js"></script>
<![endif]-->
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8">
		  	<div class="note" style="display: none;"><!--Push buttons on right--></div>
		</div>
		<div class="col-md-4">
			<div class="pull-right">
				<a id="reset" class="btn btn-default btn-xs" onclick="location.reload();"><i class="glyphicon glyphicon-refresh"></i> <?php echo $this->__("Reset")?></a>
	 			<a id="add_titan_block" class="btn btn-warning btn-xs"><i class="glyphicon glyphicon-plus"></i> <?php echo $this->__(" New Snippet")?></a>
				<a class="btn btn-info btn-xs btn-preview"><i class="glyphicon glyphicon-eye-open"></i> <?php echo $this->__("PREVIEW")?> </a>
				<a id="save_all_config" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-floppy-saved"></i> <?php echo $this->__("SAVE")?></a>
			</div>
		</div>
	</div>
</div>
<div id="wrapper">
	<!-- Left Navigation -->
	<ul id="block_list" class="nav nav-pills nav-stacked col-md-2">
	  	<li  class="active"><a href="#getstartedtitan" data-toggle="pill"><?php echo $this->__("Getting Started")?> <i class="pull-right glyphicon glyphicon-floppy-disk" aria-hidden="true"></i></a></li>
	  	<li><a href="#block_hidden-top" data-toggle="pill"><?php echo $this->__("Top Bar")?> <i class="pull-right glyphicon glyphicon-floppy-disk" aria-hidden="true"></i></a></li>
	  	<li><a href="#block_header" data-toggle="pill"><?php echo $this->__("Header")?> <i class="pull-right glyphicon glyphicon-floppy-disk" aria-hidden="true"></i></a></li>
	  	<li><a href="#block_before_main_content" data-toggle="pill"><?php echo $this->__("Before Main Content")?> <i class="pull-right glyphicon glyphicon-floppy-disk" aria-hidden="true"></i></a></li>
	  	<li><a href="#block_maincontent" data-toggle="pill"><?php echo $this->__("Sidebar")?> <i class="pull-right glyphicon glyphicon-floppy-disk" aria-hidden="true"></i></a></li>
	  	<li><a href="#block_after_main_content" data-toggle="pill"><?php echo $this->__("After Main Content")?> <i class="pull-right glyphicon glyphicon-floppy-disk" aria-hidden="true"></i></a></li>
	  	<li><a href="#block_footer" data-toggle="pill"><?php echo $this->__("Footer")?> <i class="pull-right glyphicon glyphicon-floppy-disk" aria-hidden="true"></i></a></li>
	  	<li><a href="#block_hidden-bottom" data-toggle="pill"><?php echo $this->__("Very Bottom ")?> <i class="pull-right glyphicon glyphicon-floppy-disk" aria-hidden="true"></i></a></li>
	</ul>
	<!-- End Left Navigation -->
	<!--Controls Popup-->
	<?php echo $this->getBlockHtml("titan_controls_panel"); ?>
	<!--Controls Popup-->	
	<div class="container-non-responsive_none" id="page-content-wrapper">
		<div class="tab-content" id="mainTabContent">
			<div id="mainLayout" class="tab-pane fade active in" >
				<div class="col-md-10">
					<div class="alert alert-success alert-dismissible" role="alert">
					  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					  <strong>Saved!</strong> Your configuration has been saved.
					</div>
				</div>
				<?php echo $this->getBlockHtml("titan_layout"); ?>
			</div>
		</div>
	</div>
	<!--Block Config Init-->
	<?php echo $this->getBlockHtml("titan_block_config_data"); ?>
	<div class="progress-bar" style="display: none;">
		<div class="bar"><i class="sphere"></i></div>
	</div>
	<input type="hidden" id="baseurl" value="<?php echo $this->getBaseUrl(); ?>"/>
	<input type="hidden" id="current_tab" value="<?php echo $this->getRequest()->getParam("tab") ?>"/>
	<!-- ADD BLOCK IFRAME -->
	<iframe id="add_block_iframe" src="<?php echo $this->getBaseUrl(); ?>titan/block/addBlock/new/yes/area/transforming" style="position: fixed; top: -100000px;left:-99999px;"></iframe>
</div>
<script>
//Fix conflict Prototype vs Bootstrap + jQuery
if (Prototype.BrowserFeatures.ElementExtensions) {
    var disablePrototypeJS = function (method, pluginsToDisable) {
            var handler = function (event) {
                event.target[method] = undefined;
                setTimeout(function () {
                    delete event.target[method];
                }, 0);
            };
            pluginsToDisable.each(function (plugin) { 
                jQuery(window).on(method + '.bs.' + plugin, handler);
            });
        },
        pluginsToDisable = ['collapse', 'dropdown', 'modal', 'tooltip', 'popover'];
    disablePrototypeJS('show', pluginsToDisable);
    disablePrototypeJS('hide', pluginsToDisable);
}
</script>