<?php 
$_blockKey = "left";
$blockConfig = $this->getHeaderOrFooterBlock("maincontent");
?>
<?php if (isset($blockConfig[$_blockKey])) : ?>
<!--div class="panel <?php //echo $blockConfig['width_config'] ?> "-->
	<?php foreach ($blockConfig[$_blockKey] as $gridColumns) : ?>
		<!--div class="<?php echo $gridColumns['custom_class'] ?>"-->
			<?php foreach ($gridColumns['child_blocks'] as $_childBlock) : ?>
				<?php $blockInfo = json_decode($_childBlock, true); ?>
				<div class="panel panel-default block-sidebar-<?php echo $blockInfo['id'];?>">
				  <div class="panel-heading">
					<h4 class="panel-title"> 
						<a data-toggle="collapse"  href="#block-sidebar-<?php echo $blockInfo['id'];?>" class="collapseWill"> 
							<span class="pull-left"> <i class="fa fa-caret-right"></i></span> 
							<?php echo $blockInfo['title'];?>
						</a> 
					</h4>
				  </div>
				  <div id="block-sidebar-<?php echo $blockInfo['id'];?>" class="panel-collapse collapse in">
					<div class="panel-body">
						<div class="block-content">
						<?php if ($blockInfo['type'] == "static_block") : ?>
							<?php echo Mage::getSingleton("core/layout")->createBlock("cms/block")->setBlockId($blockInfo['identifier'])->toHtml(); ?>
						<?php else : ?>
							<?php echo $this->_getBlockHtml($blockInfo); ?>
						<?php endif; ?>
						</div>
					</div>
				  </div>
				</div>
			<?php endforeach; ?>
		<!--/div-->
	<?php endforeach; ?>
<!--/div-->
<?php endif; ?>