<?php 
/* Header > Header-top */
$_blockKey = "header-top";
$blockConfig = $this->getHeaderOrFooterBlock("header");
?>
<input class="block-config-data" type="hidden" value="<?php echo htmlentities(json_encode($blockConfig)) ?>" name="data-block[<?php echo $_blockKey ?>]"/>
<?php if (isset($blockConfig[$_blockKey])) : ?>
<div class="t2-section">
	<?php foreach ($blockConfig[$_blockKey] as $gridColumns) : ?>
		<div class="<?php echo $gridColumns['custom_class'] ?>">
			<?php foreach ($gridColumns['child_blocks'] as $_childBlock) : ?>
				<?php $blockInfo = json_decode($_childBlock, true); ?>
				<?php if ($blockInfo['type'] == "static_block") : ?>
					<?php echo Mage::getSingleton("core/layout")->createBlock("cms/block")->setBlockId($blockInfo['identifier'])->toHtml(); ?>
				<?php else : ?>	
					<?php echo $this->_getBlockHtml($blockInfo); ?>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
	<?php endforeach; ?>
</div>
<?php endif; ?>