<div class="panel-heading" >
	<div class="row">
		<div class="col-lg-10"><h3 class="panel-title">AFTER MAIN CONTENT (Homepage only)</h3><small>Add sub blocks for <em>slideshow, full width background, big banner ...</em></small></div>
		<div class="col-lg-2 pull-right">
			<div class="btn-group pull-right">
				<button type="button" class="btn btn-success btn-xs btn-save-config"><?php echo $this->__("SAVE") ?></button>
			</div>
		</div>
	</div>
</div>
<div class="panel-body" id="after-main-content">
	<div class="col-lg-12 block-change" >
		<div class="block4" data-block="block4">
			<div class="row">
				<div class="col-lg-6">BLOCK 4</div>
				<div class="col-lg-6 text-right">
					<div class="btn-group pull-right">
						<a class="btn btn-primary btn-xs btn-add-column">
							<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__(" Sub Block") ?>
						</a>
						<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
							Block Width <span class="caret"></span>
						</a>
						<ul class="dropdown-menu box-width" role="menu">
						<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
						<li><a class="box-width-type" rel="t2-section-full">Full (padding 15px)</a></li>
						<li><a class="box-width-type" rel="t2-section-full no-padding">Full (no padding)</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">12 col</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> Control</a> 
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Sub Block"  ><i class="glyphicon glyphicon-remove-circle"></i> Remove</a> 				
			</div>
		</div>
	</div>
	<hr/>
	<div class="col-lg-12 block-change">
		<div class="block5" data-block="block5">
			<div class="row">
				<div class="col-lg-6">BLOCK 5</div>
				<div class="col-lg-6 text-right">
					<div class="btn-group pull-right">
						<a class="btn btn-primary btn-xs btn-add-column">
							<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__(" Sub Block") ?>
						</a>
						<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
							Block Width <span class="caret"></span>
						</a>
						<ul class="dropdown-menu box-width" role="menu">
							<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
							<li><a class="box-width-type" rel="t2-section-full">Full (padding 15px)</a></li>
							<li><a class="box-width-type" rel="t2-section-full no-padding">Full (no padding)</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">12 col</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> Control</a> 
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Sub Block"  ><i class="glyphicon glyphicon-remove-circle"></i> Remove</a> 				
			</div>
		</div>
	</div>
	<hr/>
	<div class="col-lg-12 block-change">
		<div class="block6" data-block="block6">
			<div class="row">
				<div class="col-lg-6">BLOCK 6</div>
				<div class="col-lg-6 text-right">
					
					<div class="btn-group pull-right">
						<a class="btn btn-primary btn-xs btn-add-column">
							<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__(" Sub Block") ?>
						</a>
						<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
							Block Width <span class="caret"></span>
						</a>
						<ul class="dropdown-menu box-width" role="menu">
						<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
						<li><a class="box-width-type" rel="t2-section-full">Full (padding 15px)</a></li>
						<li><a class="box-width-type" rel="t2-section-full no-padding">Full (no padding)</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">12 col</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> Control</a> 
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Sub Block"  ><i class="glyphicon glyphicon-remove-circle"></i> Remove</a> 				
			</div>
		</div>
	</div>
</div>