<div class="panel-heading">
	<div class="row">
		<div class="col-lg-10"><h3 class="panel-title">HEADER  </h3><small>Add sub blocks for <em>Logo, Site Search, Phone Numbers, Main Menu, User Account Links, Promotion banner, Dropdown Cart</em> ..etc into the sub blocks</small></div>
		<div class="col-lg-2 pull-right">
			<div  class="btn-toolbar pull-right" role="toolbar">
				<div class="btn-group">
					<a class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
						Header Width <span class="caret"></span>
						</a>
					<ul class="dropdown-menu box-width" role="menu">
					<li><a class="box-width-type" rel="t2-section">Boxed</a></li>
					<li><a class="box-width-type" rel="t2-section-full">Full (padding 15px)</a></li>
					<li><a class="box-width-type" rel="t2-section-full no-padding">Full (no padding)</a></li>
					</ul>
				</div>
				<div class="btn-group">
					<button type="button" class="btn btn-success btn-xs btn-save-config"><?php echo $this->__("SAVE") ?></button>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="panel-body" id="t2header">
	<div class="col-lg-12 block-change">
		<div class="header-top"  data-block="header-top"> 
			<div class="row">
				<div class="col-lg-10"><span>Header Top</span></div>
				<div class="col-lg-2">
					<a class="btn btn-primary pull-right btn-xs btn-add-column">
						<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__(" Sub Block") ?>
					</a>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">12 col</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> <span><?php echo $this->__("Control");?></span></a>
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Sub Block"  ><i class="glyphicon glyphicon-remove-circle"></i> <span>Remove</span></a>			
			</div>
		</div>
	</div>
	<hr/>
	<div class="col-lg-12 block-change">
		<div class="header-mid"  data-block="header-mid">
			<div class="row">
				<div class="col-lg-10"><span>Header Middle</span></div>
				<div class="col-lg-2">
					<a class="btn btn-primary pull-right btn-xs btn-add-column">
						<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__(" Sub Block") ?>
					</a>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>12 col </p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> <span>Control</span></a>
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Sub Block"  ><i class="glyphicon glyphicon-remove-circle"></i> <span>Remove</span></a>
			</div>
		</div>
	</div>
	<hr/>
	<div class="col-lg-12 block-change">
		<div class="header-bottom"  data-block="header-bottom">
			<div class="row">
				<div class="col-lg-10"><span>Header Bottom</span></div>
				<div class="col-lg-2">
					<a class="btn btn-primary pull-right btn-xs btn-add-column">
						<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__(" Sub Block") ?>
					</a>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>12 col </p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> <span>Control</span></a>
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Sub Block"  ><i class="glyphicon glyphicon-remove-circle"></i> <span>Remove</span></a>
			</div>
		</div>
	</div>
</div>