<div class="panel-heading" >
	<div class="row">
		<div class="col-lg-12"><h3 class="panel-title">Getting Started </h3><small>An overview of <em>Layout Builder</em>, how to use layout builder, import sample data and more ..</small></div>
	</div>
</div>
<div class="panel-body" id="gettingstarted">
	<div class="col-lg-12">
		<div class="row">
			<div class="col-lg-12">
			 <p>Using <strong>Layout Builder</strong> to transform theme layout by insert sub block(s) into defined <em><b>Block Structure</b></em>(Top bar, Header, Block 1 to 6, Sidebars, Footer, veryBottom), base on Bootstrap Grid system.(<a href="http://getbootstrap.com/css/#grid" target="_blank">#grid</a>, <a href="<?php echo $this->getSkinUrl('titan/structural-blocks.jpg');?>" target="_blank" >#titan-structural-blocks</a>)</p> 
			</div>
		</div>
		<div class="col-lg-6">
			<div class="panel panel-warning">
		  <div class="panel-heading"><strong>SUB BLOCK</strong></div>
		  <div class="panel-body">
			<p>Use <strong>Sub Blocks</strong> to divide structural block layout with content. Each sub-block included features below:<br/>
			<ul>
				<li><b><i>- Content</i></b>: Snippets and Static Blocks</li>
				<li><b><i>- Grid column value</i></b>: from <em>1 col</em> to <em>12 col</em></li>
				<li><b><i>- Custom class</i></b></li>
			</ul>
			</p>
			<p><span class="btn btn-xs  btn-primary"><i class="glyphicon glyphicon-plus-sign "></i> Sub Block </span> add sub-block; <span class="btn btn-xs  btn-default"><i class="glyphicon glyphicon-cog "></i> Control </span> Setting sub-block; </br></p>
			<p><span class="btn btn-xs  btn-default"><i class="glyphicon glyphicon-remove-circle "></i> Remove </span> delete sub-block (can not undo)</br></p>
		  </div>
		</div>
		</div>
		<div class="col-lg-6">
			<div class="panel panel-warning">
		  <div class="panel-heading"><strong>SNIPPET</strong></div>
		  <div class="panel-body">
			<p>A <strong>Snippet</strong> is defined content block type, you can add template content from any extension, custom static block, products list ..etc. 
		You can assign many snippets into any sub-block. </p>
		<ul>
			<li>+ Press <span class="btn btn-xs  btn-warning"><i class="glyphicon glyphicon-plus"></i> New Snippet</span> to quick create new snippet</li>
			<li>+ All snippets will be list on <em>T2 Theme > Manage Snippets</em></li>
			<li>+ You can drag and move snippets in sub-block to reorder snippets possition.</li>
			<li>+ You can assign many snippets into any sub-block.</li>
		</ul>
		  </div>
		</div>
		</div>
		<div class="col-lg-12">
			<div class="panel panel-primary">
			  <div class="panel-heading"><strong>IMPORT SAMPLE DATA</strong></div>
			  <div class="panel-body">
				<p><span class="btn btn-xs  btn-info"><i class="glyphicon glyphicon-refresh "></i> Sample Layout Builder </span></p>
				<p><span class="btn btn-xs  btn-info"><i class="glyphicon glyphicon-refresh "></i> Sample CMS/Static Block </span></br></p>
				<p><span class="btn btn-xs  btn-info"><i class="glyphicon glyphicon-refresh "></i> Sample Snippets </span></p>
			  </div>
			</div>
		</div>
		<div class="col-lg-12">
		<p>Press <span class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-floppy-saved"></i> SAVE</span> every time when you made changes.<br/>
		<em>Reference: <a href="http://www.magentocommerce.com/design_guide/articles/magento-design-terminologies4#term-blocks" target="_blank">Magento Structural Blocks and Content Blocks</a></em>
		</p> 
		</div>		
	</div>
</div>