<div class="panel-heading" >
	<div class="row">
		<div class="col-lg-12"><h3 class="panel-title">Getting Started </h3><small>An overview of <em>Layout Builder</em>, how to use layout builder, import sample data and more ..</small></div>
	</div>
</div>
<div class="panel-body" id="gettingstarted">
	<div class="col-lg-12">
		<div class="row">
			<div class="col-lg-12">
			 <p>Using <strong>Layout Builder</strong> to transform theme layout by insert sub block(s) into defined <em><b><a href="<?php echo $this->getSkinUrl('titan/structural-blocks.jpg');?>" target="_blank" >Structural Block </a></b></em>(Top bar, Header, Block 1 to 6, Sidebars, Footer, veryBottom), base on Bootstrap Grid system.(<a href="http://getbootstrap.com/css/#grid" target="_blank">#grid</a>, <a href="<?php echo $this->getSkinUrl('titan/structural-blocks.jpg');?>" target="_blank" >#titan-structural-blocks</a>)</p> 
			</div>
		</div>
		<div class="col-lg-6">
			<div class="panel panel-warning">
		  <div class="panel-heading"><strong>SUB BLOCK</strong></div>
		  <div class="panel-body">
			<p>Use <strong>Sub Blocks</strong> to divide structural block layout with content. Each sub-block included features below:<br/>
			<ul>
				<li><b><i>- Content</i></b>: Snippets and Static Blocks</li>
				<li><b><i>- Grid column value</i></b>: from <em>1 col</em> to <em>12 col</em></li>
				<li><b><i>- Custom class</i></b></li>
			</ul>
			</p>
			<p><span class="btn btn-xs  btn-primary"><i class="glyphicon glyphicon-plus-sign "></i> Sub Block </span> add sub-block; <span class="btn btn-xs  btn-default"><i class="glyphicon glyphicon-cog "></i> Control </span> Setting sub-block; </br></p>
			<p><span class="btn btn-xs  btn-default"><i class="glyphicon glyphicon-remove-circle "></i> Remove </span> delete sub-block (can not undo)</br></p>
		  </div>
		</div>
		</div>
		<div class="col-lg-6">
			<div class="panel panel-warning">
		  <div class="panel-heading"><strong>SNIPPET</strong></div>
		  <div class="panel-body">
			<p>A <strong>Snippet</strong> is defined content block type, you can add template content from any extension, custom static block, products list ..etc. 
		You can assign many snippets into any sub-block. </p>
		<ul>
			<li>+ Press <span class="btn btn-xs  btn-warning"><i class="glyphicon glyphicon-plus"></i> New Snippet</span> to quick create new snippet</li>
			<li>+ All snippets will be list on <em>T2 Theme > Manage Snippets</em></li>
			<li>+ You can drag and move snippets in sub-block to reorder snippets possition.</li>
			<li>+ You can assign many snippets into any sub-block.</li>
		</ul>
		  </div>
		</div>
		</div>
		<div class="col-lg-12">
			<div class="panel panel-primary">
			  <div class="panel-heading"><strong>EXPORT SAMPLE DATA</strong></div>
			  <div class="panel-body">
				<?php $exportUrl = Mage::helper("adminhtml")->getUrl("titan/adminhtml_layout/export"); ?>
				<p><a href="<?php echo $exportUrl ?>" class="btn btn-xs  btn-info"><i class="glyphicon glyphicon-refresh "></i> Export Current Layout </a></p>
				<ul>
					<li>+ Export all snippets</li>
					<li>+ Export current layout builder config</li>
					<li>+ Export static blocks that used in layout</li>
				</ul>
			  </div>
			  <div class="panel-heading"><strong>IMPORT SAMPLE DATA</strong></div>
			  <div class="panel-body">
				<?php $importUrl = Mage::helper("adminhtml")->getUrl("titan/adminhtml_layout/import"); ?>
				<form id="import_form" action="<?php echo $importUrl; ?>" method="post" enctype="multipart/form-data">
					<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
					<p>
						<span class="btn btn-xs btn-primary btn-file">
							<i class="glyphicon glyphicon-file "></i>
							<?php echo $this->__("Browse ...") ?> <input type="file" name="sample_data_file"/>
						</span>
						<p><a class="btn btn-xs  btn-warning" id="import_btn" onclick="document.getElementById('import_form').submit();"><i class="glyphicon glyphicon-refresh "></i> Import Layout</a></p>
					</p>
				</form>
				
				<ul>
					<li>+ Please export current layout to make a backup before importing.</li>
					<li>+ All current snippets will be removed.</li>
				</ul>
			  </div>
			</div>
		</div>
		<div class="col-lg-12">
		<p>Press <span class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-floppy-saved"></i> SAVE</span> every time when you made changes.<br/>
		<em>Reference: <a href="http://www.magentocommerce.com/design_guide/articles/magento-design-terminologies4#term-blocks" target="_blank">Magento Structural Blocks and Content Blocks</a></em>
		</p> 
		</div>		
	</div>
</div>