<div class="panel-heading" >
	<div class="row">
		<div class="col-lg-10"><h3 class="panel-title">Top Bar </h3><small>Hidden content on very top of page. Eg <em>newsletter popup</em> or <em>promotion popup</em></small></div>
		<div class="col-lg-2 pull-right">
			<div class="btn-group pull-right">
				<button type="button" class="btn btn-success btn-xs btn-save-config"><?php echo $this->__("SAVE") ?></button>
			</div>
		</div>
	</div>
</div>
<div class="panel-body" id="topbar">
	<div class="col-lg-12 block-change">
		<div class="top-bar"  data-block="top-bar">
			<div class="row">
				<div class="col-lg-10"><span>Top Bar</span></div>
				<div class="col-lg-2">
					<a class="btn btn-primary pull-right btn-xs btn-add-column">
						<span class="glyphicon glyphicon-plus-sign"></span><?php echo $this->__(" Sub Block") ?>
					</a>
				</div>
			</div>
			<div class="col-lg-12 border-dash">
				<p>
					<span class="column-num">12 col</span>				
				</p>
				<a class="btn btn-default poper" data-toggle="modal" data-target=".bs-example-modal-lg" title="Manage Snippets"  ><i class="glyphicon glyphicon-cog"></i> Control</a> 
				<a class="btn btn-default remove-col" data-toggle="tooltip" title="Remove Sub Block"  ><i class="glyphicon glyphicon-remove-circle"></i> Remove</a> 				
			</div>
		</div>
	</div>
</div>